spring:
  profiles:
    active: local
  messages: 
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: true
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false  
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

ckeditor:
  storage:
    image-path: C:/temp/image
    service-url: http://localhost:18080/image
    
---
spring:
  profiles: local
server:
  port: 18080  

---
spring:
  profiles: dev
server:
  port: 18081


