spring:
  profiles:
    active: local
  messages: 
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: true
    
---
spring:
  profiles: local
server:
  port: 18080  

---
spring:
  profiles: dev
server:
  port: 18081


